name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradlecache-${{ hashFiles('app/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradlecache-

      - name: Restore Gradle dist cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradledist-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build
        run: ./gradlew app:lintDebug app:assembleDebug --no-daemon

      - name: Copy lint reports
        if: always()
        run: |
          mkdir -p lint
          find ./app/build/reports -type f -name "lint*" -exec cp {} lint/ \;

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: lint
          path: lint

      - name: Upload debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
